version: '3'
services:
  db:
    image: postgres:11-alpine
    volumes:
    - db_data:/var/lib/postgres/data
  django_proj:
    build: .
    command: >
        bash -c "python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:7777"
    volumes:
    - django_data:/var/lib/django/data
    ports:
      - "7777:7777"
    depends_on:
      - db
volumes:
  db_data:
  django_data: